#pragma config(Motor,  port2,           frontRightMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           backLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           backRightMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//int condition = 0;
while(vexRT[Btn8U]==0){}

//allMotors
motor[frontRightMotor]= 35;
motor[backRightMotor] = 35;
motor[frontLeftMotor] = 35;
motor[backLeftMotor] = 35;
wait1Msec(1400000);
}
