#pragma config(Sensor, dgtl1,  frontSensor,    sensorTouch)
#pragma config(Motor,  port2,           frontRightMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           PanelMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           ElevatorTopMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           backLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           backRightMotor, tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  while(1 == 1)

    //Right side of the robot is controlled by the right joystick, Y-axis
    motor[frontRightMotor] = vexRT[Ch2];
    motor[backRightMotor]  = vexRT[Ch2];
    //Left side of the robot is controlled by the left joystick, Y-axis
    motor[frontLeftMotor] = vexRT[Ch3];
    motor[backLeftMotor]  = vexRT[Ch3];

    //Elevator Control
    if(vexRT[Btn6U] == 1)
    {
      motor[ElevatorTopMotor] = 80;
    }
    else if(vexRT[Btn6D] == 1)
    {
      motor[ElevatorTopMotor] = -80;
    }
    else
    {
      motor[ElevatorTopMotor] = 0;
    }

    //Panel Control
    if(vexRT[Btn5U] == 1)
    {
      motor[PanelMotor] = 80;
    }
    else if(vexRT[Btn5D] == 1)
    {
      motor[PanelMotor] = -80;
    }
    else
    {
      motor[PanelMotor] = 0;
    }


 }
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
