#pragma config(Motor,  port2,           frontRightMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           backLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           backRightMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



void turnLeft(int time){
	//turnLeft
motor[frontRightMotor]= 35;
motor[backRightMotor] = 35;
motor[frontLeftMotor] = 0;
motor[backLeftMotor] = 0;
wait1Msec(time);

}

void turnRight(int time){

//turnRight
motor[frontRightMotor]= 0;
motor[backRightMotor] = 0;
motor[frontLeftMotor] = 35;
motor[backLeftMotor] = 35;
wait1Msec(time);

}

void allMotors(int time){


//allMotors
motor[frontRightMotor]= 35;
motor[backRightMotor] = 35;
motor[frontLeftMotor] = 35;
motor[backLeftMotor] = 35;
wait1Msec(time);

}

task main()
{


while(vexRT[Btn8U]==0){
	}

 allMotors(615);

 turnLeft(900);

 allMotors(600);

 turnRight(1100);

 allMotors(550);

 turnRight(1130);

 allMotors(580);

 turnLeft(1000);

 allMotors(590);

 turnLeft(1040);






 allMotors(600);

 turnRight(1170);

 allMotors(600);

 turnRight(1150);

allMotors(666);

turnRight(1100);

allMotors(630);

turnRight(1155);

allMotors(750);

turnLeft(1000);

allMotors(600);

turnLeft(900);

allMotors(666);

turnRight(1100);

allMotors(550);

turnRight(1250);

allMotors(950);

turnLeft(1030);

allMotors(1500);

}
