#pragma config(Sensor, dgtl4,  frontSensor,    sensorTouch)
#pragma config(Motor,  port2,           frontRightMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           backLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           backRightMotor, tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void moveForward()
{
	motor[frontRightMotor] = 25;
 	motor[backRightMotor]  = 25;
  motor[frontLeftMotor] = 25;
  motor[backLeftMotor]  = 25;
}


void turnRight(int time) {
	//go back first
	motor[frontRightMotor] = -25;
 	motor[backRightMotor]  = -25;
  motor[frontLeftMotor] = -25;
 	motor[backLeftMotor]  = -25;
  wait1Msec(750);
  //then make turn
  motor[frontRightMotor] = 0;
  motor[backRightMotor]  = 0;
  motor[frontLeftMotor] = 35;
  motor[backLeftMotor]  = 35;
  wait1Msec(time);
  //go back again
	motor[frontRightMotor] = -25;
 	motor[backRightMotor]  = -25;
  motor[frontLeftMotor] = -25;
 	motor[backLeftMotor]  = -25;
  wait1Msec(1400);
}
void turnLeft(int time) {
	//go back first
	motor[frontRightMotor] = -25;
  motor[backRightMotor]  = -25;
  motor[frontLeftMotor] = -25;
  motor[backLeftMotor]  = -25;
  wait1Msec(750);
  //then make turn
  motor[frontRightMotor] = 35;
  motor[backRightMotor]  = 35;
  motor[frontLeftMotor] = 0;
  motor[backLeftMotor]  = 0;
  wait1Msec(time);
  //go back again
	motor[frontRightMotor] = -25;
 	motor[backRightMotor]  = -25;
  motor[frontLeftMotor] = -25;
 	motor[backLeftMotor]  = -25;
  wait1Msec(1400);
}



task main()
{
	while(vexRT[Btn8U] == 0){}

	while(SensorValue(frontSensor) == 0) {
	//move forward
	moveForward();
	}



  while (SensorValue(frontSensor) == 1) {
		//Front Sensor Left
    turnLeft(1100);
  }

  while (SensorValue(frontSensor) == 0){
		//move forward
		moveForward();
	}

  while (SensorValue(frontSensor) == 1) {

//Front Sensor Left
   	turnLeft(1100);
  }



  while (SensorValue(frontSensor) == 0){
		//move forward
		moveForward();
	}


  while (SensorValue(frontSensor) == 1) {
		//Front Sensor Right
  	turnRight(900);
  }



  while (SensorValue(frontSensor) == 0){
		//move forward
		moveForward();
	}


  while (SensorValue(frontSensor) == 1) {

		//Front Sensor Right
  	turnRight(900);
  }


 	while (SensorValue(frontSensor) == 0){
		//move forward
		moveForward();
	}

	while (SensorValue(frontSensor) == 1) {
		//Front Sensor Right
		turnRight(900);
  }


  while (SensorValue(frontSensor) == 0){
		//move forward
		moveForward();
	}

  while (SensorValue(frontSensor) == 1) {
		//Front Sensor Left
  	turnLeft(1100);
  }

  while (SensorValue(frontSensor) == 0) {
  	moveForward();
  }

}
